In [1]:
# Import data
import pandas as pd
data = pd.read_csv('/Users/rdrobinson/Cambridge/boe-financial-analysis/notebooks/rachel/All_in_one/Surprise_Test/sentiment_classification_output_JPM.csv')

In [2]:
data.head(10)

,bank,quarter,call_type,call_date,position_in_call,section,speaker_role,speaker_name,speaker_institution,sentence_id,...,FBT_Main_Sentiment,FBT_Main_Sentiment_Score,FBT_Positive,FBT_Negative,FBT_Neutral,RBT_main_sentiment,RBT_main_sentiment_score,RBT_negative,RBT_neutral,RBT_positive
0,JPM,2022-Q1,earnings,2022-04-13,1,prepared,operator,Operator,NaN,38069,...,Neutral,0.999224,0.000347,4.287062e-04,9.992242e-01,RBT_positive,0.730632,0.003520,0.265848,0.730632
1,JPM,2022-Q1,earnings,2022-04-13,1,prepared,operator,Operator,NaN,38070,...,Neutral,0.999934,0.000016,5.006634e-05,9.999342e-01,RBT_neutral,0.727711,0.145285,0.727711,0.127004
2,JPM,2022-Q1,earnings,2022-04-13,1,prepared,operator,Operator,NaN,38071,...,Neutral,0.998818,0.000049,1.133684e-03,9.988177e-01,RBT_neutral,0.687097,0.270609,0.687097,0.042294
3,JPM,2022-Q1,earnings,2022-04-13,1,prepared,operator,Operator,NaN,38072,...,Neutral,0.999986,0.000002,1.230122e-05,9.999856e-01,RBT_neutral,0.849775,0.035288,0.849775,0.114936
4,JPM,2022-Q1,earnings,2022-04-13,1,prepared,operator,Operator,NaN,38074,...,Neutral,0.996093,0.000050,3.856973e-03,9.960935e-01,RBT_neutral,0.897147,0.023675,0.897147,0.079178
5,JPM,2022-Q1,earnings,2022-04-13,1,prepared,operator,Operator,NaN,38075,...,Neutral,0.998143,0.000679,1.177751e-03,9.981427e-01,RBT_neutral,0.626841,0.041853,0.626841,0.331306
6,JPM,2022-Q1,earnings,2022-04-13,2,prepared,management,Jeremy Barnum,NaN,38078,...,Neutral,0.997522,0.000070,2.407933e-03,9.975223e-01,RBT_neutral,0.872353,0.049872,0.872353,0.077774
7,JPM,2022-Q1,earnings,2022-04-13,2,prepared,management,Jeremy Barnum,NaN,38079,...,Neutral,0.999697,0.000226,7.732767e-05,9.996969e-01,RBT_neutral,0.890833,0.024900,0.890833,0.084267
8,JPM,2022-Q1,earnings,2022-04-13,2,prepared,management,Jeremy Barnum,NaN,38080,...,Neutral,0.999783,0.000039,1.781695e-04,9.997825e-01,RBT_neutral,0.904025,0.050316,0.904025,0.045659
9,JPM,2022-Q1,earnings,2022-04-13,2,prepared,management,Jeremy Barnum,NaN,38081,...,Positive,1.000000,1.000000,1.246612e-09,9.590874e-09,RBT_positive,0.705291,0.002490,0.292219,0.705291

In [3]:
# Drop rows where 'main_emotion" is anger, fear, joy, sadness or love
surprise_data = data[~data['main_emotion'].isin(['anger', 'fear', 'joy', 'sadness', 'love'])]

In [5]:
surprise_data.shape

(40, 39)

In [16]:
# Create dataframe with sentences and speakers and quarters
sentences_df = surprise_data[['speaker_name', 'speaker_role','sentence', 'quarter']]

# Sort by quarter and then speaker role
sentences_df = sentences_df.sort_values(by=['quarter', 'speaker_role'])
sentences_df.head(40)

,speaker_name,speaker_role,sentence,quarter
403,Jamie Dimon,management,...you'd be shocked.,2022-Q1
415,Jamie Dimon,management,And you're always going to be a little surpris...,2022-Q1
635,Glenn Schorr,analyst,And just curious on how you thought about that.,2022-Q2
1434,Charles W. Peabody,analyst,I'm just curious in your guidance on NII where...,2022-Q3
1370,Jamie Dimon,management,And I was surprised to see how much leverage t...,2022-Q3
1666,Glenn Schorr,analyst,I'm curious – I want to talk leveraged loans f...,2022-Q4
1671,Glenn Schorr,analyst,I'm curious to see if things have gotten cheap...,2022-Q4
2410,Glenn Schorr,analyst,I'm curious on your thoughts around how custom...,2023-Q1
3538,Mike Mayo,analyst,I understand the NII strategy benefited from F...,2023-Q3
3501,Jeremy Barnum,management,I'm personally a little bit more pessimistic a...,2023-Q3
3847,Erika Najarian,analyst,I'm wondering what guideposts you're looking f...,2023-Q4
3929,Gerard Cassidy,analyst,"And second, are you surprised that QT hasn't b...",2023-Q4
4197,Jim Mitchell,analyst,"It sounds like it's migration, but just I'd be...",2024-Q1
4255,Jamie Dimon,management,I just don't think any of us should be surpris...,2024-Q1
4787,Glenn Schorr,analyst,"So, I'm curious if you're showing more progres...",2024-Q2
4804,Glenn Schorr,analyst,"Now, it seems like you have tons of excess liq...",2024-Q2
4818,Matt O'Connor,analyst,I was just wondering if you can elaborate on e...,2024-Q2
4696,Jeremy Barnum,management,"Interesting question, Steve.",2024-Q2
4782,Jeremy Barnum,management,"And so, it's not entirely surprising that you'...",2024-Q2
5494,Betsy L. Graseck,analyst,I'm just wondering about private label credit ...,2024-Q3
5439,Jamie Dimon,management,"I can't tell you exactly when, but I'd be surp...",2024-Q3
5857,Matt O'Connor,analyst,But I guess I'm just wondering like is it wort...,2024-Q4
5931,Ebrahim H. Poonawala,analyst,I'm just wondering if you have any thoughts th...,2024-Q4
5972,Jeremy Barnum,management,"If anyone has a different opinion, we're alway...",2024-Q4
6403,Betsy L. Graseck,analyst,So I'm just wondering if there was some line d...,2025-Q1
6496,Glenn Schorr,analyst,Just curious to get your big picture thoughts.,2025-Q1
6208,Jeremy Barnum,management,So it's not that surprising that you're seeing...,2025-Q1
6209,Jeremy Barnum,management,The other thing that people are kind of intere...,2025-Q1
6665,Christopher McGratty,analyst,I'm interested in what's on or off the table i...,2025-Q2
7085,Glenn Schorr,analyst,So I'm curious if there's a higher level of co...,2025-Q2
7107,Glenn Schorr,analyst,I'm just curious if there's a valuation limita...,2025-Q2
7048,Jeremy Barnum,management,I think I personally was a little bit surprise...,2025-Q2
7049,Jamie Dimon,management,I was not surprised.,2025-Q2
7643,Jim Mitchell,analyst,"So, just curious your thoughts.",2025-Q3
7694,Ken Usdin,analyst,"So, I'm just wondering if you'd kind of walk u...",2025-Q3
7329,Jeremy Barnum,management,"And obviously, as we've been discussing a lot ...",2025-Q3
7624,Jamie Dimon,management,But I think what you should do is – and I thin...,2025-Q3
7629,Jamie Dimon,management,"Every now and then, we see what someone else i...",2025-Q3
7858,Ken Usdin,analyst,I was just wondering – and we can see that in ...,2025-Q4
7859,Ken Usdin,analyst,But I'm just wondering we have your NII outloo...,2025-Q4